### ISSUE TITLE
Undefined properties error

### ISSUE THREAD

**Issue by drding00** [islu/Which-Egg-Is-Which#11]
![image](https://github.com/islu/Which-Egg-Is-Which/assets/1434928/057f9e39-0e81-4074-a98c-96200165b892)

I hopped on DC this morning and noticed the eggs were back to their mystery image, so I came and grabbed the latest update, reloaded the extension and the error above popped up. 

I'm currently running version 3.2.0

**Comment by ZeroHrsprs** [comment]
Just got this same error after noticing the images were no longer showing and came here to see if anyone else had this issue.  Reloading has pretty much always worked for me, but no dice this time. The codes are still showing properly in the AP, though.

**Comment by islu** [comment]
The reason for the issue is that the URL has changed.

<img width="261" alt="" src="https://github.com/islu/Which-Egg-Is-Which/assets/38793955/effb4257-18b8-4d3b-b212-0f3454a114e5">

I will fix this, thank you for the report.

**Comment by drding00** [comment]
Just downloaded the 3.2.1 patch and the egg images are showing again! 

There's an error being flagged in the extensions manager:
![image](https://github.com/islu/Which-Egg-Is-Which/assets/1434928/a0d36702-0442-48ec-a050-a7f9e64e0ac6)

But as far as I can tell it isn't effecting the plugin's functionality.

**Comment by islu** [comment]
I think it's a lingering effect of a previous error. You can clear it. It's okay if it doesn't reappear.

**Comment by drding00** [comment]
okay! thanks so much!
