### ISSUE TITLE
About new features: highlight & show lineage on abandoned egg

### ISSUE THREAD

**Issue by Corneliarhine** [islu/Which-Egg-Is-Which#3]
This is a very convenient feature.But could the lineage viewing window be placed elsewhere? Now it will change the position of the egg on the page and then make you accidentally click to something else.

**Comment by islu** [comment]
That's right!
> Now it will change the position of the egg on the page and then make you accidentally click to something else.

I change lineage viewing position. Now, it will show on ads block. Maybe I will change another position.

**Comment by Corneliarhine** [comment]
> That's right!
> 
> > Now it will change the position of the egg on the page and then make you accidentally click to something else.
> 
> I change lineage viewing position. Now, it will show on ads block. Maybe I will change another position.

This is a very important and meaningful improvement. Thank you for your adjustment!
