### ISSUE TITLE
Thunder dragon image not replaced

### ISSUE THREAD

**Issue by Olodhin** [islu/Which-Egg-Is-Which#9]
Bear in mind, I've not done much with JS at all. But I assume you have the location/biome of each egg and match it's description with its image. I just had a thunder dragon egg that didn't show an image for.

I assume it's due to a slight error in the egg description.
The one listed in the [Egg/Identification guide](https://dragcave.fandom.com/wiki/Egg/Identification_guide) on the wiki matches that in location.js:
"Whenever you go near this egg your hair stands on end."

Whereas the description for the egg in the actual [Thunder Dragon](https://dragcave.fandom.com/wiki/Thunder_Dragon) page reads:
"Whenever you go near this egg, your hair stands on end."

I imagine it's due to the minor grammatical difference.

**Comment by islu** [comment]
I did refer to location.js and match it's description with its image.

I will fix this, thank you for the report.
